### ISSUE TITLE
Add compatibility with Simsat framework

### ISSUE THREAD

**Issue by ydaveluy** [ThalesGroup/xsmp-modeler-core#13] opened 2023-03-24 09:33 UTC
Provide a profile to develop components based on the [Simsat framework](https://gitlab.space-codev.org/sim/simsat-kernel/-/tree/10.3).

This profile should:
- customize the C++ generator
- provide a project wizard
- add specific validation rules if any restriction with Simsat CDK

Document the setup to install Simsat and how to use it in XSMP

**Comment by ydaveluy** [comment] 2023-03-29 19:26
Hello,

I pushed a first draft for a SimSat profile in branch [13-add-compatibility-with-simsat-framework](https://github.com/ThalesGroup/xsmp-modeler-core/tree/13-add-compatibility-with-simsat-framework).

It is still incomplete: I do not have simsat and cdk installed and I am not familiar with the simsat framework.

@aingenito-telespazio: Could you provide instructions on how to install simsat ?

**Comment by aingenito-telespazio** [comment] 2023-03-30 08:37
Unfortunately Space-CODEV Gitlab is under maintenance this morning. And I'm still waiting for it to start.

Meanwhile, I have a couple of feedback. The cat to xcat conversion should really be from cli, if only to be able to copy past the errors :-).
I have a couple of screenshots:

![image](https://user-images.githubusercontent.com/129275358/228778212-dc29dd99-535d-447f-abb0-e116b02959be.png)
![image](https://user-images.githubusercontent.com/129275358/228778505-ddfbbeda-f615-455b-94ac-07eae4f86c24.png)

So second feedback, it would be nice for the error to use names where possible.
In this case it is the first element so it's easy. The converter did not like our Const metadata:

```
              <Metadata xsi:type="Types:Attribute" Id="_18_4_1_126903bf_1593759091128_309885_14400.Const" Name="Const">
                <Type xlink:title="Const" xlink:href="http://www.ecss.nl/smp/2019/Smdl#Smp.Attributes.Const"/>
                <Value xsi:type="Types:BoolValue" Value="true"/>
              </Metadata>
```

So likely the problem is `http://www.ecss.nl/smp/2019/Smdl#Smp.Attributes.Const`

**Comment by aingenito-telespazio** [comment] 2023-03-30 08:54
Found the bug :-)

It looks like the reference used in xsmp doesn't match the catalogue on Smp (or at least the one I have available).

In my SMP catalogue I have:
```
      <Type xsi:type="Types:AttributeType" Id="Smp.Attributes.Const" Name="Const"
            Visibility="public"
            Uuid="8596d697-fb84-41ce-a685-6912006ed6c5">
```

So, the id should be `Smp.Attributes.Const`.
But the generator uses `<Type xlink:title="Const" xlink:href="http://www.ecss.nl/smp/2019/Smdl#Attributes.Const"/>`

**Comment by ydaveluy** [comment] 2023-03-30 09:20
The conversion from smpcat to xsmpcat requires to include files from SMP which are under community licence.

You can follow theses [instructions](https://github.com/ThalesGroup/xsmp-modeler-core/blob/3d78eb1f0b698c7778d0da7d1b4a3c04a167939c/org.eclipse.xsmp.tool.smp/resources/org/eclipse/xsmp/tool/smp/lib/README)

It should resolve some of your unresolved reference.

**Comment by ydaveluy** [comment] 2023-03-30 09:37
In the generator this [part](https://github.com/ThalesGroup/xsmp-modeler-core/blob/3d78eb1f0b698c7778d0da7d1b4a3c04a167939c/org.eclipse.xsmp.tool.smp/src/org/eclipse/xsmp/tool/smp/generator/SmpGenerator.java#L277) is commented.

It should resolve the invalid Attributes reference. This hack is ugly... I have to find a better way to solve this.

**Comment by aingenito-telespazio** [comment] 2023-03-31 06:52
@ydaveluy Here's a primer on approaching SIMULUS build.
The easiest way to handle prerequisites is to use the containers in https://gitlab.space-codev.org/sim/containers or to replicate the steps in a machine. Of course other distributions work as well, but apt-get commands have to be translated (and GCC needs to be between 7 and 11 included).

The instructions to build are normally in https://sim.space-codev.org/docs/10.3.0/simulus/cig/introduction/. However it would be useful to look at the updates in this branch https://gitlab.space-codev.org/sim/simulus/-/blob/feature_issue_2-improvements-to-simulus-cig/Documentation/cig/introduction.md until it is merged.

Note: it looks like CODEV server is going to be in maintenance tomorrow (01.04.2023), I would recommend cloning everything today.

For any issue or question don't hesitate to ask!

**Comment by aingenito-telespazio** [comment] 2023-03-31 08:03
> The conversion from smpcat to xsmpcat requires to include files from SMP which are under community licence.
> 
> You can follow theses [instructions](https://github.com/ThalesGroup/xsmp-modeler-core/blob/3d78eb1f0b698c7778d0da7d1b4a3c04a167939c/org.eclipse.xsmp.tool.smp/resources/org/eclipse/xsmp/tool/smp/lib/README)
> 
> It should resolve some of your unresolved reference.

I can confirm that it works :-)
The catalogue import spotted a valid issue in the test catalogue (extensions). And generated the xsmpcat.
The generated xsmpcat has errors, but I leave to @ydaveluy if this should go in a separate issue to track. Perhaps after he has SIMULUS available to try out the conversion.

**Comment by ydaveluy** [comment] 2023-05-09 18:21
Hello @aingenito-telespazio,
The versim project was a good candidate to test some advanced features of the standard.
We are almost ready to release an rc2 with a profile compatible with the Simsat CDK.
The import of smpcat file is now really better.
The generated xsmpcat for versim has errors:
- some types are not visible: the standard is not clear about the visibility of types. In xsmp a public type is visible from everywhere, a protected type is visible only in the enclosing catalogue and a private type is only visible in the enclosing namespace.
 - default values with invalid designated fields (e.g: { .x=0, .y=2, ...}
 - entrypoint with input fields which are not input.
Can you confirm that theses errors are valid ?
After correction we successfully generated the source code with the embedded code generator. The generated code compile and tests are ok with minors modification of the user code.

Just a remark about cmakelist.txt files defined in ecss-smp. It seems to be "old" cmake style files, it would be great to provide an ecss-smpConfig.cmake: it would be more easy to integrate the CDK in a "generic" environment and to use [find_package](https://cmake.org/cmake/help/latest/command/find_package.html) from other cmakelist.

FYI with my OS with a very recent GCC version (13.1) ecss-smp build but tests failed with an exception. Tests are ok with a docker image with an older version of GCC.

Yannick

**Comment by aingenito-telespazio** [comment] 2023-05-10 06:32
Hello @ydaveluy, it's true that we parked XSMP activities at the moment (as we are finalising 10.3 and 11.3 release). But I hope to resume it soon.

For the issues:
* my understanding on UMF generation is that the visibility on types is used in generation for certain operations (e.g. making the constructor public/protected/private). I'm honestly not sure about what is the *right* behaviour, if there is any. It is worth consulting the WG1 and possibly make a RID on SMP.
* Can you give me an example of invalid default fields (which element in the catalogue is affected)? When the system is working the json-like definitions should become a `<FieldValue/>` in catalogue. I could not find one where this did not happen [here](https://gitlab.space-codev.org/sim/ecss-smp/-/blob/10.3/Src/esa.ecss.smp.versim/umf/esa.ecss.smp.versim.smpcat).
* Also for this, do you have an example? This may just be an error in design that is not reported by UMF.

Regarding modernising the CMakeList.txt. I would be happy to, in fact I was also looking at dependency tools meant to replace how we use Maven. Can I recommend to open it as an issue in CODEV? This will not have a lot of priority in the next few months (I'd rather push ESA to integrate XSMP in the process), but it is a very good point that should be recorded.

Finally for GCC. So far I could only test successfully SIMULUS with GCC 11.x. I start getting problems with GCC 12.x. This is also a task that has been deferred until after 10.3/11.3. For the next release we just mark as a limitation.

**Comment by aingenito-telespazio** [comment] 2023-05-10 08:50
@ydaveluy  I see!

`privChar8Field` initialises these was using GetField, bypassing the private. I'm not sure here UMF is in the wrong here. I will find some time to check the standard.

For EntryPoint inputs instead, I can see how UMF could be in the wrong. There is no real handling in UMF code generation for input fields of entry points.

For "Log" we are definitely bending the rules in favour of developer convenience. A Log message as both static and instance configuration, and we only want to configure the static part in design. This could be migrated to a more appropriate usage of catalogue (moving the information to metadata).

**Closed** 2023-05-15 12:56 UTC
Labels: enhancement
